// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aliases.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAlias = `-- name: CreateAlias :one
INSERT INTO aliases (
    id, alias, url_code
)
VALUES ($1, $2, $3)
RETURNING id, alias, url_code, created_at
`

type CreateAliasParams struct {
	ID      uuid.UUID
	Alias   string
	UrlCode string
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (Alias, error) {
	row := q.db.QueryRowContext(ctx, createAlias, arg.ID, arg.Alias, arg.UrlCode)
	var i Alias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.UrlCode,
		&i.CreatedAt,
	)
	return i, err
}

const getUrlOwnerByAlias = `-- name: GetUrlOwnerByAlias :one
SELECT u.user_id
FROM aliases a
         JOIN urls u ON u.short_code = a.url_code
WHERE a.alias = $1
LIMIT 1
`

func (q *Queries) GetUrlOwnerByAlias(ctx context.Context, alias string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUrlOwnerByAlias, alias)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
