// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAnalyticsData = `-- name: CreateAnalyticsData :exec
INSERT INTO analytics (
    id, short_code, alias, clicked_at, ip, country, referrer, device, os, browser
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAnalyticsDataParams struct {
	ID        uuid.UUID
	ShortCode string
	Alias     sql.NullString
	ClickedAt time.Time
	Ip        string
	Country   string
	Referrer  sql.NullString
	Device    string
	Os        string
	Browser   string
}

func (q *Queries) CreateAnalyticsData(ctx context.Context, arg CreateAnalyticsDataParams) error {
	_, err := q.db.ExecContext(ctx, createAnalyticsData,
		arg.ID,
		arg.ShortCode,
		arg.Alias,
		arg.ClickedAt,
		arg.Ip,
		arg.Country,
		arg.Referrer,
		arg.Device,
		arg.Os,
		arg.Browser,
	)
	return err
}
