// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_aggregation.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getClickEventData = `-- name: GetClickEventData :one

SELECT
    a.short_code,
    a.alias,
    a.clicked_at,
    a.ip,
    a.country,
    a.city,
    a.referrer,
    a.device,
    a.browser,
    u.user_id
FROM analytics a
JOIN urls u ON u.short_code = a.short_code
WHERE a.short_code = $1
  AND a.clicked_at = $2
  AND a.ip = $3
LIMIT 1
`

type GetClickEventDataParams struct {
	ShortCode string
	ClickedAt time.Time
	Ip        string
}

type GetClickEventDataRow struct {
	ShortCode string
	Alias     sql.NullString
	ClickedAt time.Time
	Ip        string
	Country   string
	City      string
	Referrer  sql.NullString
	Device    string
	Browser   string
	UserID    uuid.UUID
}

// Helper queries to get aggregated data for a single click event
func (q *Queries) GetClickEventData(ctx context.Context, arg GetClickEventDataParams) (GetClickEventDataRow, error) {
	row := q.db.QueryRowContext(ctx, getClickEventData, arg.ShortCode, arg.ClickedAt, arg.Ip)
	var i GetClickEventDataRow
	err := row.Scan(
		&i.ShortCode,
		&i.Alias,
		&i.ClickedAt,
		&i.Ip,
		&i.Country,
		&i.City,
		&i.Referrer,
		&i.Device,
		&i.Browser,
		&i.UserID,
	)
	return i, err
}

const upsertAliasBrowser = `-- name: UpsertAliasBrowser :exec
INSERT INTO analytics_alias_browser (short_code, alias, browser, total_clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (short_code, alias, browser)
DO UPDATE SET
    total_clicks = analytics_alias_browser.total_clicks + EXCLUDED.total_clicks
`

type UpsertAliasBrowserParams struct {
	ShortCode   string
	Alias       string
	Browser     string
	TotalClicks int32
}

func (q *Queries) UpsertAliasBrowser(ctx context.Context, arg UpsertAliasBrowserParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliasBrowser,
		arg.ShortCode,
		arg.Alias,
		arg.Browser,
		arg.TotalClicks,
	)
	return err
}

const upsertAliasDaily = `-- name: UpsertAliasDaily :exec

INSERT INTO analytics_alias_daily (short_code, alias, date, total_clicks, unique_visitors)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (short_code, alias, date)
DO UPDATE SET
    total_clicks = analytics_alias_daily.total_clicks + EXCLUDED.total_clicks,
    unique_visitors = EXCLUDED.unique_visitors
`

type UpsertAliasDailyParams struct {
	ShortCode      string
	Alias          string
	Date           time.Time
	TotalClicks    int32
	UniqueVisitors int32
}

// Alias-level aggregation queries
func (q *Queries) UpsertAliasDaily(ctx context.Context, arg UpsertAliasDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliasDaily,
		arg.ShortCode,
		arg.Alias,
		arg.Date,
		arg.TotalClicks,
		arg.UniqueVisitors,
	)
	return err
}

const upsertAliasDevice = `-- name: UpsertAliasDevice :exec
INSERT INTO analytics_alias_device (short_code, alias, device, total_clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (short_code, alias, device)
DO UPDATE SET
    total_clicks = analytics_alias_device.total_clicks + EXCLUDED.total_clicks
`

type UpsertAliasDeviceParams struct {
	ShortCode   string
	Alias       string
	Device      string
	TotalClicks int32
}

func (q *Queries) UpsertAliasDevice(ctx context.Context, arg UpsertAliasDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliasDevice,
		arg.ShortCode,
		arg.Alias,
		arg.Device,
		arg.TotalClicks,
	)
	return err
}

const upsertAliasGeo = `-- name: UpsertAliasGeo :exec
INSERT INTO analytics_alias_geo (short_code, alias, country, city, total_clicks)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (short_code, alias, country, city)
DO UPDATE SET
    total_clicks = analytics_alias_geo.total_clicks + EXCLUDED.total_clicks
`

type UpsertAliasGeoParams struct {
	ShortCode   string
	Alias       string
	Country     string
	City        string
	TotalClicks int32
}

func (q *Queries) UpsertAliasGeo(ctx context.Context, arg UpsertAliasGeoParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliasGeo,
		arg.ShortCode,
		arg.Alias,
		arg.Country,
		arg.City,
		arg.TotalClicks,
	)
	return err
}

const upsertAliasReferrer = `-- name: UpsertAliasReferrer :exec
INSERT INTO analytics_alias_referrer (short_code, alias, referrer, total_clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (short_code, alias, referrer)
DO UPDATE SET
    total_clicks = analytics_alias_referrer.total_clicks + EXCLUDED.total_clicks
`

type UpsertAliasReferrerParams struct {
	ShortCode   string
	Alias       string
	Referrer    string
	TotalClicks int32
}

func (q *Queries) UpsertAliasReferrer(ctx context.Context, arg UpsertAliasReferrerParams) error {
	_, err := q.db.ExecContext(ctx, upsertAliasReferrer,
		arg.ShortCode,
		arg.Alias,
		arg.Referrer,
		arg.TotalClicks,
	)
	return err
}

const upsertURLBrowser = `-- name: UpsertURLBrowser :exec
INSERT INTO analytics_url_browser (short_code, browser, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (short_code, browser)
DO UPDATE SET
    total_clicks = analytics_url_browser.total_clicks + EXCLUDED.total_clicks
`

type UpsertURLBrowserParams struct {
	ShortCode   string
	Browser     string
	TotalClicks int32
}

func (q *Queries) UpsertURLBrowser(ctx context.Context, arg UpsertURLBrowserParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLBrowser, arg.ShortCode, arg.Browser, arg.TotalClicks)
	return err
}

const upsertURLDaily = `-- name: UpsertURLDaily :exec

INSERT INTO analytics_url_daily (short_code, date, total_clicks, unique_visitors)
VALUES ($1, $2, $3, $4)
ON CONFLICT (short_code, date)
DO UPDATE SET
    total_clicks = analytics_url_daily.total_clicks + EXCLUDED.total_clicks,
    unique_visitors = EXCLUDED.unique_visitors
`

type UpsertURLDailyParams struct {
	ShortCode      string
	Date           time.Time
	TotalClicks    int32
	UniqueVisitors int32
}

// URL-level aggregation queries
func (q *Queries) UpsertURLDaily(ctx context.Context, arg UpsertURLDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLDaily,
		arg.ShortCode,
		arg.Date,
		arg.TotalClicks,
		arg.UniqueVisitors,
	)
	return err
}

const upsertURLDevice = `-- name: UpsertURLDevice :exec
INSERT INTO analytics_url_device (short_code, device, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (short_code, device)
DO UPDATE SET
    total_clicks = analytics_url_device.total_clicks + EXCLUDED.total_clicks
`

type UpsertURLDeviceParams struct {
	ShortCode   string
	Device      string
	TotalClicks int32
}

func (q *Queries) UpsertURLDevice(ctx context.Context, arg UpsertURLDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLDevice, arg.ShortCode, arg.Device, arg.TotalClicks)
	return err
}

const upsertURLGeo = `-- name: UpsertURLGeo :exec
INSERT INTO analytics_url_geo (short_code, country, city, total_clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (short_code, country, city)
DO UPDATE SET
    total_clicks = analytics_url_geo.total_clicks + EXCLUDED.total_clicks
`

type UpsertURLGeoParams struct {
	ShortCode   string
	Country     string
	City        string
	TotalClicks int32
}

func (q *Queries) UpsertURLGeo(ctx context.Context, arg UpsertURLGeoParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLGeo,
		arg.ShortCode,
		arg.Country,
		arg.City,
		arg.TotalClicks,
	)
	return err
}

const upsertURLReferrer = `-- name: UpsertURLReferrer :exec
INSERT INTO analytics_url_referrer (short_code, referrer, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (short_code, referrer)
DO UPDATE SET
    total_clicks = analytics_url_referrer.total_clicks + EXCLUDED.total_clicks
`

type UpsertURLReferrerParams struct {
	ShortCode   string
	Referrer    string
	TotalClicks int32
}

func (q *Queries) UpsertURLReferrer(ctx context.Context, arg UpsertURLReferrerParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLReferrer, arg.ShortCode, arg.Referrer, arg.TotalClicks)
	return err
}

const upsertUserBrowser = `-- name: UpsertUserBrowser :exec
INSERT INTO analytics_user_browser (user_id, browser, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, browser)
DO UPDATE SET
    total_clicks = analytics_user_browser.total_clicks + EXCLUDED.total_clicks
`

type UpsertUserBrowserParams struct {
	UserID      uuid.UUID
	Browser     string
	TotalClicks int32
}

func (q *Queries) UpsertUserBrowser(ctx context.Context, arg UpsertUserBrowserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserBrowser, arg.UserID, arg.Browser, arg.TotalClicks)
	return err
}

const upsertUserDaily = `-- name: UpsertUserDaily :exec

INSERT INTO analytics_user_daily (user_id, date, total_clicks, unique_visitors)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, date)
DO UPDATE SET
    total_clicks = analytics_user_daily.total_clicks + EXCLUDED.total_clicks,
    unique_visitors = EXCLUDED.unique_visitors
`

type UpsertUserDailyParams struct {
	UserID         uuid.UUID
	Date           time.Time
	TotalClicks    int32
	UniqueVisitors int32
}

// User-level aggregation queries
func (q *Queries) UpsertUserDaily(ctx context.Context, arg UpsertUserDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserDaily,
		arg.UserID,
		arg.Date,
		arg.TotalClicks,
		arg.UniqueVisitors,
	)
	return err
}

const upsertUserGeo = `-- name: UpsertUserGeo :exec
INSERT INTO analytics_user_geo (user_id, country, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, country)
DO UPDATE SET
    total_clicks = analytics_user_geo.total_clicks + EXCLUDED.total_clicks
`

type UpsertUserGeoParams struct {
	UserID      uuid.UUID
	Country     string
	TotalClicks int32
}

func (q *Queries) UpsertUserGeo(ctx context.Context, arg UpsertUserGeoParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserGeo, arg.UserID, arg.Country, arg.TotalClicks)
	return err
}

const upsertUserTopLinks = `-- name: UpsertUserTopLinks :exec
INSERT INTO analytics_user_top_links (user_id, short_code, total_clicks)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, short_code)
DO UPDATE SET
    total_clicks = analytics_user_top_links.total_clicks + EXCLUDED.total_clicks
`

type UpsertUserTopLinksParams struct {
	UserID      uuid.UUID
	ShortCode   string
	TotalClicks int32
}

func (q *Queries) UpsertUserTopLinks(ctx context.Context, arg UpsertUserTopLinksParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserTopLinks, arg.UserID, arg.ShortCode, arg.TotalClicks)
	return err
}
