// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO password_reset (
    id, user_id, hashed_token, expires_at
)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	HashedToken string
	ExpiresAt   time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.HashedToken,
		arg.ExpiresAt,
	)
	return err
}

const getToken = `-- name: GetToken :one
SELECT user_id, expires_at, used FROM password_reset
WHERE hashed_token = $1
`

type GetTokenRow struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
	Used      bool
}

func (q *Queries) GetToken(ctx context.Context, hashedToken string) (GetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getToken, hashedToken)
	var i GetTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt, &i.Used)
	return i, err
}

const setUsed = `-- name: SetUsed :exec
UPDATE password_reset
SET used = true
`

func (q *Queries) SetUsed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setUsed)
	return err
}
